fix script

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -27,10 +27,25 @@ steps:
   - ./src/defid -daemon
   - sleep 20
   - ./src/defi-cli getblockchaininfo
-  - chmod +x ci/wait_for_blocks.sh 
+  - |
+    sh -c '
+    block=0
+    attempts=0
+    while [ $block -lt 10000 ]; do
+        sleep 5
+        b=$(./src/defi-cli getblockchaininfo | jq '.blocks' )
+        block=$${b:-$block}
+        echo "===> Block Height $block"
+        if [ $attempts -gt 12 ]; then
+            echo "Failed to bootstrap after a minute."
+            exit 1
+        fi
+        attempts=$(($attempts + 1))
+    done    
+    '
   - ./ci/wait_for_blocks.sh
 - name: teardown
-  comands:
+  commands:
   - ./src/defi-cli stop
   - sudo pkill -f -9 defid
   when:
